### PR TITLE
Update CSV data for a new format

### PR DESCRIPTION
**Pull request by arvaki**
SYMP table format had been changed somewhere before macOS Catalina beta 7.

Also I've made some minor changes non-related to the subject.

### CODE REVIEW

**Comment by auramagi** [comment]
It will probably keep getting updated as Apple releases new symbols.

If we want to keep a copy of the table in this repo, it's probably better to either

1. Come up with some naming scheme to keep all different versions together. "Old-new" will get out of hand.
2. Keep only the latest copy and rely on git versioning (that way it's easy to see diffs).

🤔

**Comment by arvaki** [comment]
I would prefer the first option. 

Here is the best idea I have at the moment:

SF Symbols | macOS | iOS | ... | Notes
---|---|---|---|---
[v1-beta]() | 10.15 beta | 13.0 beta | ... | `SF Symbols.app/Contents/Resources/SFSymbolsFallback.ttf` contained a different data [v1-beta-fallback]()
[v1]() | 10.15 | 13.0 | ... | -
*v2* | *10.16* | *14.0* | ... | -
*v2.1* | *10.16.xx* | *14.xx* | ... | -

It seems to me that new symbols (or new font files format) would always be a part of OS release, so this scheme should work.

The second option has downsides if you need to explore older SF Symbols versions:
- you cannot clone with `depth=1`
- you have to make extra actions to view the CSV files.

**Comment by auramagi** [comment]
I removed the commit that updated csv data — I'll do that myself.
As to naming, I think I'll go with the internal font versioning scheme (e.g. 15.0d7e11) and make a table in a readme file that links to everything.

**Comment by auramagi** [comment]
I think I will go with the internal font versioning (e.g. 15.0d7e11) and make a table in a readme file that links to everything.
I'll accept your other changes if you remove the commit that updates the csv data from this PR.

**Comment by arvaki** [comment]
Your versioning scheme is much better.
The commit has been removed.

**Pull request merged**
